runtime: php55
api_version: 1

handlers:
    - url: /login
      script: login.php
    
    - url: /main
      script: main.php
    
    - url: /name
      script: name.php

    - url: /password
      script: password.php